<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>smv</string>
	</array>
	<key>name</key>
	<string>SMV</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Strings</string>
			<key>match</key>
			<string>(")([A-Za-z0-9\~\!\@\#\$\%\^\&amp;\*\(\)\_\+\`\-\=]+)(")</string>
			<key>name</key>
			<string>string.quoted.smv</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Range</string>
			<key>match</key>
			<string>(\d+)(\.\.)(\d+)</string>
			<key>name</key>
			<string>string.other.instance.constructor</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>(\d+\.?\d+)</string>
			<key>name</key>
			<string>constant.language.smv</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>^\s*(--)\s*.*</string>
			<key>name</key>
			<string>comment.line.smv</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\s*(VAR|ASSIGN|TRANS)\s*</string>
			<key>name</key>
			<string>keyword.control.smv</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.smv</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.function.smv</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.smv</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Module keyword</string>
			<key>match</key>
			<string>\s*(MODULE|module)\s*([A-Za-z0-9\_]+)\s*\(?\s*([A-Za-z0-9][A-Za-z0-9\_,\s]*[A-Za-z0-9\_])?\s*\)?\s*</string>
			<key>name</key>
			<string>keyword.definition.module.smv</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.variable.smv</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variables</string>
			<key>match</key>
			<string>([a-zA-Z][A-Za-z0-9\_]*)</string>
			<key>name</key>
			<string>variable.language.smv</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.smv</string>
	<key>uuid</key>
	<string>29010fa9-35fc-4496-82d7-87d4e29d16d3</string>
</dict>
</plist>
